# https://www.appveyor.com/docs/appveyor-yml/
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

image: Ubuntu

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

build_script:
  - dotnet --info
  - dotnet build -c Release

after_build:
  - dotnet publish helloWorld -c Release -r ubuntu-x64 /p:PublishSingleFile=true -o ./artifacts
  - ls artifacts

test_script:
  - dotnet test ./*.Test

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

artifacts:
  - path: artifacts\helloWorld
    name: ReleaseArtifacts
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  # Deploy to GitHub Releases
  # # provider: Environment
  # name: "release env"

  - provider: GitHub
    # tag: $(APPVEYOR_REPO_TAG_NAME)
    # artifact: ReleaseArtifacts
    # force_update: true
    description: 'Release description'
    # release: $(appveyor_repo_tag_name)
    draft: false
    prerelease: false
    # auth_token: 7137bb1e9bea557f17b59b6c0fbff3b9a77cecd7
    auth_token:
      secure: 84VwVYVnUliNjxPLmOCPbm3WK7T+ZXMsP1uk+zoeD1bl7iBlMtiZzCvnjkqeDtVV
    on:
      branch: master
      # appveyor_repo_tag: false
      # do_rel: true
      # APPVEYOR_REPO_TAG: true       # deploy on tag push only
    # artifact: helloWorld/bin/Release/netcoreapp3.1/ubuntu-x64/publish/helloWorld           # upload all NuGet packages to release assets
    # artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
