# https://www.appveyor.com/docs/appveyor-yml/
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
# version: 1.0.{build}

# os to use
image:
  - Visual Studio 2019
  - Ubuntu
# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

dotnet_csproj:
  patch: true
  file: 'helloWorld\*.csproj'
  version: '{version}'

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

build:
  project: helloWorld.sln
  verbosity: minimal
  # configuration: Release
  publish_nuget: false
  publish_aspnet_core: false
  publish_core_console: true

build_script:
  - dotnet --info
  - dotnet build -c Release

after_build:
  # change "helloWorld" by the project folder name
  - sh: dotnet publish helloWorld -c Release -r ubuntu-x64 /p:PublishSingleFile=true -o ./artifacts
  - cmd: dotnet publish helloWorld -c Release -r win10-x64 /p:PublishSingleFile=true -o ./artifacts
  - ls artifacts
  - rm artifacts/*.pdb

test_script:
  - sh: dotnet test ./*.Test
  - cmd: dotnet test

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

artifacts:
  - path: artifacts\*
    name: ReleaseArtifacts
# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  # Deploy to GitHub Releases

  - provider: GitHub
    # tag: $(APPVEYOR_REPO_TAG_NAME)
    artifact: ReleaseArtifacts
    # force_update: true
    description: 'Release description'
    # release: $(appveyor_repo_tag_name)
    draft: false
    prerelease: false
    auth_token:
      secure: hcbPO46qyB0R/KZWfwGR4sVt8keXe52HZ+VeiC+MoeLkF50OBIZ1C0bT6EDzs0by
    on:
      branch: master
      # appveyor_repo_tag: false
      # do_rel: true
      # APPVEYOR_REPO_TAG: true       # deploy on tag push only
    # artifact: helloWorld/bin/Release/netcoreapp3.1/ubuntu-x64/publish/helloWorld           # upload all NuGet packages to release assets
    # artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
